title: 'MIKU 10th'
alt: '#初音ミク MIKU 10th - 帽捲的插畫'
id: 64737486
date: 2017-09-01
category: 創作
parody: '原創'
characters: []
tags: ['初音ミク', 'VOCALOID', '初音ミク生誕祭2017', '初音ミク10周年']
rating: all
fav: 20
featured: false
cover: 01.png
pages:
  - 01.png
