title: '[STUDIO MAOCHINN (帽捲)] 遊戲動畫二創輯 [フルカラー]'
alt: 'Game & anime fanart collection'
id: 265918
date: 2019-01-01
category: 創作
parody: '綜合'
characters: ['2B', '黑貞德', '酒吞童子']
tags: ['二創', '插畫', '電繪']
rating: all
fav: 2789
featured: true
cover: 01.png
pages:
  - 01.png
  - 02.png
  - 03.png
  - 04.png
  - 05.png
  - 06.png
  - 07.png
  - 08.png
