title: 'EGOIST!'
alt: '#EGOIST EGOIST! - 帽捲的插畫'
id: 56179393
date: 2016-04-03
category: 創作
parody: '原創'
characters: []
tags: ['EGOIST', 'chelly', '祈']
rating: all
fav: 3
featured: false
cover: 01.png
pages:
  - 01.png
