title: '初音 EXPO 2016 IN TAIWAN 賀圖'
alt: '#初音 初音 EXPO 2016 IN TAIWAN 賀圖 - 帽捲的插畫'
id: 57663367
date: 2016-06-30
category: 創作
parody: '原創'
characters: []
tags: ['初音', '同人', '初音ミク']
rating: all
fav: 1
featured: false
cover: 01.png
pages:
  - 01.png
