title: '在座有病，小短漫'
alt: '#同人 在座有病，小短漫 - 帽捲的漫畫 #漫画 #在座寫輕小說的各位,全都有病 #雛雪'
id: 71878424
date: 2018-11-28
category: 創作
parody: '原創'
characters: []
tags: ['漫画', '同人', '在座寫輕小說的各位,全都有病', '雛雪']
rating: all
fav: 14
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
