title: 'K/DA kai''sa'
alt: '#同人 K/DA kai''sa - 帽捲的插畫'
id: 71613981
date: 2018-11-11
category: 創作
parody: '原創'
characters: []
tags: ['同人', 'LOL', 'KDA', 'K/DA']
rating: all
fav: 15
featured: false
cover: 01.png
pages:
  - 01.png
