title: 'Pokemon 赤/黑'
alt: '#同人 Pokemon 赤/黑 - 帽捲的插畫'
id: 79821276
date: 2020-03-01
category: 創作
parody: '原創'
characters: []
tags: ['同人', '狂三', 'デート・ア・ライブ', '約會大作戰', 'pokemon', 'ポケモン']
rating: all
fav: 33
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
