title: '狂三-草稿'
alt: '#約會大作戰 狂三-草稿 - 帽捲的插畫'
id: 58285522
date: 2016-08-06
category: 創作
parody: '原創'
characters: []
tags: ['約會大作戰', 'デート・ア・ライブ', '狂三']
rating: all
fav: 19
featured: false
cover: 01.png
pages:
  - 01.png
