title: '[STUDIO MAOCHINN (帽捲)] 人體與素描研究 [習作]'
alt: 'Figure & grayscale study'
id: 228922
date: 2018-11-01
category: 練習
parody: '原創'
characters: []
tags: ['練習', '人體', '素描']
rating: all
fav: 404
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
  - 03.png
  - 04.png
  - 05.png
