title: '2017新年'
alt: '#初音 2017新年 - 帽捲的插畫'
id: 61145215
date: 2017-01-27
category: 創作
parody: '原創'
characters: []
tags: ['初音', '同人', '初音未来', '初音ミク']
rating: all
fav: 5
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
