title: '凛 誕生日'
alt: '#遠坂凛 凛 誕生日 - 帽捲的插畫'
id: 67085324
date: 2018-02-02
category: 創作
parody: '原創'
characters: []
tags: ['遠坂凛', 'Fate/staynight', 'Fate', '同人']
rating: all
fav: 11
featured: false
cover: 01.png
pages:
  - 01.png
