title: '費莉斯-封面'
alt: '#オリジナル 費莉斯-封面 - 帽捲的插畫'
id: 63578459
date: 2017-06-26
category: 創作
parody: '原創'
characters: []
tags: ['オリジナル', '原創', '銀髮']
rating: all
fav: 5
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
