title: 'Mori Calliope Happy Birthday'
alt: '#Calliope Mori Calliope Happy Birthday - 帽捲的插畫'
id: 88949241
date: 2021-04-05
category: 創作
parody: '原創'
characters: []
tags: ['Calliope', 'Callillust', 'Hololive']
rating: all
fav: 14
featured: false
cover: 01.jpg
pages:
  - 01.jpg
  - 02.jpg
