title: '世大運應援-230'
alt: '#同人 世大運應援-230 - 帽捲的插畫'
id: 64643239
date: 2017-08-27
category: 創作
parody: '原創'
characters: []
tags: ['同人', '世大運', '少女', 'ユニバーシアード']
rating: all
fav: 4
featured: false
cover: 01.png
pages:
  - 01.png
