title: '小光'
alt: '#同人 小光 - 帽捲的插畫'
id: 58692164
date: 2016-08-28
category: 創作
parody: '原創'
characters: []
tags: ['同人', 'ポケモン', 'ヒカリ(トレーナー)', 'ヒカリ', 'ポケモンコーディネーター', 'アニポケ', 'ポケアニDP', 'ヒカリ(アニポケ)']
rating: all
fav: 41
featured: false
cover: 01.png
pages:
  - 01.png
