title: '39 Day'
alt: '#初音 39 Day - 帽捲的插畫'
id: 61831014
date: 2017-03-09
category: 創作
parody: '原創'
characters: []
tags: ['初音', 'miku', '39', 'hatsune', 'vocaloid', 'ミクの日', '初音ミク']
rating: all
fav: 41
featured: false
cover: 01.png
pages:
  - 01.png
