title: '艾蜜莉亞'
alt: '#E.M.T 艾蜜莉亞 - 帽捲的插畫'
id: 57728743
date: 2016-07-03
category: 創作
parody: '原創'
characters: []
tags: ['E.M.T', 'Re:ゼロから始める異世界生活', 'エミリア', 'エミリア(リゼロ)', 'ゼロから始める異世界生活', 'リゼロ', '艾米莉亚', '艾蜜莉亞', '同人']
rating: all
fav: 37
featured: false
cover: 01.png
pages:
  - 01.png
  - 02.png
